### ISSUE TITLE
upkeep: avoid setting `GlobalEnv` variables in functions

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/pacta.portfolio.utils#28] opened 2024-03-25 08:09 UTC
Probably better to do this explicitly for each path, rather than abstracting it into a function called for it's side effects? 
Likely requires changes in https://github.com/RMI-PACTA/workflow.transition.monitor

https://github.com/RMI-PACTA/pacta.portfolio.utils/blob/2286152a9a09db7c59740157a9f1ffd5e36bd8db/R/set_web_parameters.R#L4-L7

**Comment by cjyetman** [comment] 2024-03-25 08:24
The intention is to completely deprecate this and similar functions once workflow.transition.monitor is laid to rest
- see #19 

workflow.pacta already works without these functions and captures all parameters in a single `cfg` global variable
https://github.com/RMI-PACTA/workflow.pacta/blob/77f6ee025d06265e7ab412f01497773f1d812701/pacta_01.R#L25-L32

gonna close this as a duplicate of #19

**Closed as completed by cjyetman** 2024-03-25 08:24 UTC
